"""change money columns to numeric

Revision ID: 991e86e02732
Revises: d252ed487432
Create Date: 2024-09-08 15:28:09.534192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '991e86e02732'
down_revision = 'd252ed487432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.MONEY(),
               existing_nullable=False)

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.MONEY(),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.MONEY(),
               existing_nullable=False)

    # ### end Alembic commands ###
