name: Run Tests

on:
  push:
    branches:
      - main  # Change this to your target branch (default is main)
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: myuser  # Replace with your PostgreSQL user
          POSTGRES_PASSWORD: mypassword  # Replace with your PostgreSQL password
          POSTGRES_DB: mydatabase  # Replace with your target database name
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export DATABASE_URL=postgresql://myuser:mypassword@localhost:5432/mydatabase  # Ensure this line reflects your credentials
          pytest tests/
